[package]
name = "aoc-2023-17"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[features]
p2 = []

[dependencies]
pathfinding = { workspace = true }

[lints]
workspace = true
