[package]
name = "aoc-2023-11"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[features]
p2 = []

[dependencies]

[lints]
workspace = true
