[package]
name = "aoc-2023-05"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[features]
p2 = ["dep:rayon"]

[dependencies.rayon]
version = "^1.8.0"
optional = true

[lints]
workspace = true
