[package]
name = "aoc-2023-19"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[features]
p2 = []

[dependencies]
regex = { workspace = true }

[lints]
workspace = true
