[package]
name = "aoc-2023-20"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[features]
p2 = ["dep:num"]

[dependencies.num]
workspace = true
optional = true

[lints]
workspace = true
